---
- name: Master Setup
  user: pirate
  hosts: masters
  
  tasks:
    - name: Copy kubeadm-config.yaml
      template:
        src: templates/masters/kubeadm-config.yaml
        dest: /home/pirate/kubeadm-config.yaml

    - name: Kubeadm init Master1
      when: inventory_hostname == 'master1'
      become: yes
      command: kubeadm init --config kubeadm-config.yaml --upload-certs
      tags: kubeadm_init

    - name: Create a directory if it does not exist
      file:
        path: $HOME/.kube
        state: directory
        mode: '0755'
      tags: kubeadm_config

    - name: Copy config file
      become: yes
      command: cp /etc/kubernetes/admin.conf /home/pirate/.kube/config
      tags: kubeadm_config

    - name: Chown file
      become: true
      file:
        path: /home/pirate/.kube/config
        owner: pirate
        group: pirate
      tags: kubeadm_config
