---
- name: Baseline Nodes
  user: pirate
  hosts: lb2

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes

    - name: Check Docker apt-mark hold
      command: apt-mark showhold -v
      register: docker_hold

    - name: Hold Docker Version
      become: true
      command: aptitude hold docker-ce
      when: '"docker-ce" not in docker_hold.stdout'

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
